### ISSUE TITLE
Request for sending pulses from RPI to Wallbox-Jukebox

### ISSUE THREAD

**Issue by BlueForrest** [gshorten/sonos_wallbox#1]
Hi, Found you're contribution to convert a wallbox into a sonos player very interesting.
Yet I don't have a wallbox, but I do have a jukebox AMI-H 200 select.

In fact I just want to make the opposite from what you have done = making my RPI as a remote control to control my jukebox.

So i need a small program the when I enter a key combination (keyboard input) ex. B3, the RPI will send some pulses out on one of the GPIO pins.
I see in the code that you captured the pulses, but I would like to create those pulses and send to my jukebox.   (first sending Letters, then numbers)
Ex Letter B = 2 pulses, a wait time, then Xn pulses (according the given numbers)
Ouput of the GPIO pin will trigger a relais.
The jukebox then will think a wallbox is connected and will play that song.
For the hardware I'm able to manage that, but the software is my problem.
I'm not so good in programming, so I thought you could help me out making this.

Please let me know if that is something you can do or help.

thank you

Johan

**Comment by BlueForrest** [comment]
Hi, just one more question:
whats the difference between file wb_stable_R23.py and wb_stable_R26.py ?

I'll see if I can make a small program myself (based upon your code) and send that to you for verification/correction.

**Comment by BlueForrest** [comment]
Sorry - github is also new for me

**Comment by gshorten** [comment]
Hi Blueforest... Not sure I can help much, but what you want to do is a very cool idea... use a raspberry pi as a remote jukebox controller. in principle it is pretty simple... you don't need any of the soco stuff to do this.  the code in python would be very simple, you need a keypad of some sort or touch screen.  The pi would put out 3.3v logic pulses of the right length to a custom board which would toggle a 24v ac line that goes to the jukebox, .  off the top of my head you would use simple relay to switch the 24v ac (supplied by a transformer).  probably use an opto coupler to isolate the pi from the 24v.  relay like this on digikey: https://www.digikey.ca/product-detail/en/kemet/EE2-3NUH-L/399-11006-2-ND/4291072 
Or, even better, use an off the shelf interface board like this one on Adafruit:https://www.adafruit.com/product/3289   it switches 24v, isolates the pi.  it also accepts 24 v in... now that I see that I think i might buy one and use it instead of my circuit!
Adafruit also has a bunch of displays, keyboards, interface products too.

**Comment by gshorten** [comment]
Re, versions... ignore,I am actually on a dev branch now... have not updated master.  Sonos changed some stuff, broke my code, I have to re-write!   but functions that decode pulses still work, but playing radio stations etc does not.

**Comment by BlueForrest** [comment]
Hi,  Thanks for the reply, meanwhile I have a prototype that i build myself running.  
Made a small website from where I can make selections that are send to the jukebox.
Once finished & stable I'm upload on gitHub.
